import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "components/sections/hero";
import { HowTo } from "components/sections/howTo";
import { Box } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <Box maxW="77rem" mx="auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <HowTo />
      </main>
    </Box>
  );
};

export default Home;
